# Generated by Django 4.1.7 on 2023-03-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_imdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_image_url',
            field=models.TextField(default='123'),
            preserve_default=False,
        ),
    ]
