# Generated by Django 4.1.7 on 2023-07-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_review_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
